### ISSUE TITLE
[Kafka]Create a 2 node Kafka cluster

### ISSUE THREAD

**Issue by authorjapps** [authorjapps/wordcount-k8#2]
AC1:
===
+ Create a Kafka cluster
+ Create a topic called `sentence`
+ Deploy it to a cloud

**Comment by authorjapps** [comment]
> Deploy it to a cloud

Has dependency on #8

**Comment by rpayal** [comment]
Tried on WordCounterConsumer with in 1 node K8S cluster and it worked.
